name: gaecds_improve
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.15.2
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cpython=3.9.21
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.55
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - et_xmlfile=2.0.0
  - filelock=3.17.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h5py=3.12.1
  - hdf5=1.14.3
  - intel-openmp=2022.0.1
  - jinja2=3.1.5
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libaec=1.1.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.13.0.11
  - libcurand=10.3.9.55
  - libcurl=8.11.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - lzo=2.10
  - markupsafe=3.0.2
  - mkl=2020.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.2.1
  - numexpr=2.7.3
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openpyxl=3.1.5
  - openssl=3.4.0
  - packaging=24.2
  - pip=25.0
  - py-cpuinfo=9.0.0
  - pytables=3.9.2
  - python=3.9.21
  - python_abi=3.9
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - setuptools=75.8.0
  - snappy=1.2.1
  - sympy=1.13.3
  - tk=8.6.13
  - torchtriton=2.2.0
  - typing_extensions=4.12.2
  - wheel=0.45.1
  - yaml=0.2.5
  - zlib-ng=2.2.3
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dgl==2.1.0
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - idna==3.10
      - importlib-resources==6.5.2
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - numpy==1.23.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.3
      - pillow==11.1.0
      - psutil==6.1.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - six==1.17.0
      - threadpoolctl==3.5.0
      - torch==2.2.1
      - torchdata==0.7.1
      - tqdm==4.67.1
      - tzdata==2025.1
      - urllib3==2.3.0
      - zipp==3.21.0
